const employeeData = {
    "Avani Vaidya": "SUP,FS",
    "Rohan Mishra": "PFM",
    "Vivek Raj": "PFM",
    "Aksatha S": "PRD",
    "Vivek Yadav": "CH",
    "Vikram Rajawat": "FS,DEVOPS,LEAD",
    "Rupinder Kaur Kahlon": "LEAD,SUP",
    "Gayatri Yadav": "SUP,CH",
    "Bhavya Gajera": "CH",
    "Avinash Shinde": "FS,PM",
    "Shakshi Thakur": "DEVOPS",
    "Shivam Sharma": "FS",
    "Darsh Badodariya": "PFM",
    "Siddharudh Holikatti": "PFM",
    "Disha Shah": "PRD,PFM",
    "Harsh Shah": "LEAD,PFM",
    "Dipen Sirsat": "CH",
    "Abhilash Dupargude": "PM",
    "Utkarsha Pandit": "SUP,FS",
    "Rinisha Rastogi": "SUP,PFM",
    "Jenil Vagadiya": "FS",
    "Mohit Gupta": "PFM",
    "Nehal Gahlot": "PROCESS",
    "Arun Asok": "PRD,FS",
    "Krishna Chaitanya Terala": "PFM",
    "Ajinkya Kshirsagar": "LEAD,CH,TXC",
    "Prashan P": "FS",
    "Manasi Sahasrabudhe": "HR"
};
